### ISSUE TITLE
Deploy ODH on OCP Cluster

### ISSUE THREAD

**Issue by arthomasredhat** [redhat-manufacturing/edge-lab-gitops#7]

**Comment by codekow** [comment]
Related to #5

**Comment by jarcher** [comment]
where is the ODH URL?

**Comment by codekow** [comment]
ODH is not setup yet. ODH v1.4 has many different issues.

Recommend to delay deployment of v1.4.

**Comment by arthomasredhat** [comment]
@thomasphall Do you have an update on this?

**Comment by codekow** [comment]
RHODS has been deployed in place of ODH.
